"""EDA notebook template (builder spec) for kaggle-ml-loop.

`build_notebooks.py` imports this module and calls `notebook_cells(ctx)` to get an
ordered list of (kind, source) cells. Code cells reference the runtime globals that
the generator injects as the first "parameters" cell (COMPETITION, TRAIN_CSV, TARGET,
ID_COL, RUN_DIR, MLFLOW_URI, MLFLOW_DB, links, ...). Markdown cells are f-strings
filled from `ctx` at build time.

Edit this file to change what every EDA notebook contains — the generator stays
generic. Keep code cells defensive (guard on column presence) so the same template
works across competitions, not just Titanic.
"""
from __future__ import annotations


def notebook_cells(ctx: dict) -> list[tuple[str, str]]:
    C = ctx  # link/values dict from the generator
    cells: list[tuple[str, str]] = []
    md = lambda s: cells.append(("markdown", s))
    code = lambda s: cells.append(("code", s))

    # 1. Header + links -------------------------------------------------------
    md(f"""# 📊 EDA — {C['competition']}

**Run:** `{C['timestamp']}`  ·  generated by the `kaggle-ml-loop` skill

This notebook is the visual companion to the pipeline's `eda/` outputs. Every chart
reads the raw training data directly, so it re-runs standalone.

### Links
| What | Where |
|---|---|
| Training data | [`{C['train_rel']}`]({C['train_rel']}) |
| Test data | [`{C['test_rel']}`]({C['test_rel']}) |
| Run config | [`{C['config_rel']}`]({C['config_rel']}) |
| Run directory | [`{C['run_rel']}`]({C['run_rel']}) |
| EDA report (md) | [`{C['eda_report_rel']}`]({C['eda_report_rel']}) |
| EDA summary (json) | [`{C['eda_summary_rel']}`]({C['eda_summary_rel']}) |

### MLflow experiment tracking
Launch the UI to browse every run for this competition:
```bash
mlflow ui --backend-store-uri {C['mlflow_uri']}
```
Then open **{C['mlflow_ui_url']}** in your browser.
""")

    # Setup cell
    code("""import json, warnings
from pathlib import Path
import numpy as np, pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
warnings.filterwarnings("ignore")

sns.set_theme(style="whitegrid", context="talk")
PALETTE = "crest"
sns.set_palette(sns.color_palette(PALETTE, 8))
plt.rcParams["figure.dpi"] = 110
plt.rcParams["axes.titleweight"] = "bold"

train = pd.read_csv(TRAIN_CSV)
print(f"{COMPETITION}: {train.shape[0]} rows x {train.shape[1]} columns")
train.head()""")

    # 2. Shape / dtypes / missingness ----------------------------------------
    md("## 1 · Shape, types, and missingness")
    code("""def overview(df):
    o = pd.DataFrame({
        "dtype": df.dtypes.astype(str),
        "n_unique": df.nunique(),
        "missing": df.isna().sum(),
        "missing_pct": (df.isna().mean() * 100).round(2),
    })
    return o.sort_values("missing_pct", ascending=False)

overview(train)""")

    code("""# Missingness heatmap — where are the holes?
miss = train.isna()
if miss.any().any():
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.heatmap(miss, cbar=False, cmap="mako", ax=ax)
    ax.set_title("Missing values (yellow = present, dark = missing)")
    ax.set_xlabel(""); plt.tight_layout(); plt.show()
else:
    print("No missing values.")""")

    # 3. Target distribution --------------------------------------------------
    md("## 2 · Target distribution")
    code("""fig, ax = plt.subplots(figsize=(6, 4))
vc = train[TARGET].value_counts().sort_index()
sns.barplot(x=vc.index.astype(str), y=vc.values, ax=ax, hue=vc.index.astype(str), legend=False)
for i, v in enumerate(vc.values):
    ax.text(i, v, f"{v}\\n({v/len(train):.1%})", ha="center", va="bottom")
ax.set_title(f"{TARGET} class balance"); ax.set_xlabel(TARGET); ax.set_ylabel("count")
sns.despine(); plt.tight_layout(); plt.show()""")

    # 4. Univariate -----------------------------------------------------------
    md("## 3 · Univariate distributions")
    code("""num_cols = [c for c in train.columns
            if c not in (TARGET, ID_COL) and train[c].dtype.kind in "biufc"]
cat_cols = [c for c in train.columns
            if c not in (TARGET, ID_COL) and c not in num_cols and train[c].nunique() <= 12]

if num_cols:
    n = len(num_cols); ncol = 3; nrow = int(np.ceil(n/ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5*ncol, 3.4*nrow))
    for ax, c in zip(np.atleast_1d(axes).ravel(), num_cols):
        sns.histplot(train[c].dropna(), kde=True, ax=ax, color=sns.color_palette(PALETTE)[3])
        ax.set_title(c)
    for ax in np.atleast_1d(axes).ravel()[n:]:
        ax.set_visible(False)
    fig.suptitle("Numeric feature distributions", y=1.02, fontweight="bold")
    sns.despine(); plt.tight_layout(); plt.show()""")

    code("""if cat_cols:
    n = len(cat_cols); ncol = 3; nrow = int(np.ceil(n/ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5*ncol, 3.4*nrow))
    for ax, c in zip(np.atleast_1d(axes).ravel(), cat_cols):
        order = train[c].value_counts().index
        sns.countplot(data=train, x=c, order=order, ax=ax, hue=c, legend=False)
        ax.set_title(c); ax.tick_params(axis="x", rotation=30)
    for ax in np.atleast_1d(axes).ravel()[n:]:
        ax.set_visible(False)
    fig.suptitle("Low-cardinality categorical counts", y=1.02, fontweight="bold")
    sns.despine(); plt.tight_layout(); plt.show()
else:
    print("No low-cardinality categoricals.")""")

    # 5. Bivariate vs target --------------------------------------------------
    md("""## 4 · Relationship with the target

Rate of the positive class within each group (with 95% CI). Bars that separate
strongly are the features a model will lean on.""")
    code("""is_binary = train[TARGET].nunique() == 2
drivers = [c for c in cat_cols if c != TARGET]
if is_binary and drivers:
    n = len(drivers); ncol = 3; nrow = int(np.ceil(n/ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5*ncol, 3.6*nrow))
    for ax, c in zip(np.atleast_1d(axes).ravel(), drivers):
        sns.barplot(data=train, x=c, y=TARGET, ax=ax, errorbar=("ci", 95),
                    hue=c, legend=False)
        ax.axhline(train[TARGET].mean(), ls="--", color="grey", lw=1)
        ax.set_title(f"{TARGET} rate by {c}"); ax.set_ylabel(f"P({TARGET})")
        ax.tick_params(axis="x", rotation=30)
    for ax in np.atleast_1d(axes).ravel()[n:]:
        ax.set_visible(False)
    fig.suptitle("Survival/positive-rate by category (dashed = base rate)",
                 y=1.02, fontweight="bold")
    sns.despine(); plt.tight_layout(); plt.show()""")

    code("""# Numeric features split by target class
if is_binary and num_cols:
    show = num_cols[:6]
    n = len(show); ncol = 3; nrow = int(np.ceil(n/ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(5*ncol, 3.6*nrow))
    for ax, c in zip(np.atleast_1d(axes).ravel(), show):
        sns.boxplot(data=train, x=TARGET, y=c, ax=ax, hue=TARGET, legend=False)
        ax.set_title(f"{c} by {TARGET}")
    for ax in np.atleast_1d(axes).ravel()[n:]:
        ax.set_visible(False)
    fig.suptitle("Numeric distributions split by target", y=1.02, fontweight="bold")
    sns.despine(); plt.tight_layout(); plt.show()""")

    # 6. Correlation ----------------------------------------------------------
    md("## 5 · Correlation structure")
    code("""corr_df = train[num_cols + [TARGET]].copy()
if corr_df.shape[1] > 1:
    corr = corr_df.corr(numeric_only=True)
    fig, ax = plt.subplots(figsize=(1.1*len(corr)+2, 1.0*len(corr)+1))
    sns.heatmap(corr, annot=True, fmt=".2f", cmap="vlag", center=0,
                square=True, cbar_kws={"shrink": .8}, ax=ax)
    ax.set_title("Correlation matrix (numeric + target)")
    plt.tight_layout(); plt.show()""")

    code("""# Top absolute correlation with the target
if TARGET in train.columns and num_cols:
    tc = train[num_cols + [TARGET]].corr(numeric_only=True)[TARGET].drop(TARGET)
    tc = tc.reindex(tc.abs().sort_values(ascending=False).index)
    fig, ax = plt.subplots(figsize=(7, max(3, 0.5*len(tc))))
    sns.barplot(x=tc.values, y=tc.index, ax=ax, hue=tc.index, legend=False, palette="vlag")
    ax.axvline(0, color="grey", lw=1)
    ax.set_title(f"Correlation with {TARGET}"); ax.set_xlabel("Pearson r"); ax.set_ylabel("")
    sns.despine(); plt.tight_layout(); plt.show()""")

    # 7. Engineered-feature previews (why the recipes) -----------------------
    md("""## 6 · Engineered-feature previews — *why these recipes*

These are the high-ROI derivations the feature-engineering agents target. Each is
computed here purely for visualization (target-free), so you can see the survival
signal each one exposes before the pipeline builds it. Titanic-specific cells no-op
on other competitions.""")
    code("""eng = train.copy()

# Title from Name (Titanic)
if "Name" in eng.columns:
    eng["Title"] = eng["Name"].str.extract(r",\\s*([^\\.]+)\\.")
    rare = eng["Title"].value_counts()[lambda s: s < 10].index
    eng["Title"] = eng["Title"].replace(list(rare), "Rare")

# FamilySize / IsAlone
if {"SibSp", "Parch"}.issubset(eng.columns):
    eng["FamilySize"] = eng["SibSp"] + eng["Parch"] + 1
    eng["FamilyBucket"] = pd.cut(eng["FamilySize"], [0, 1, 4, 100],
                                 labels=["alone", "small", "large"])
    eng["IsAlone"] = (eng["FamilySize"] == 1).astype(int)

# Ticket group size + fare per person
if "Ticket" in eng.columns:
    eng["TicketGroupSize"] = eng.groupby("Ticket")["Ticket"].transform("count")
    if "Fare" in eng.columns:
        eng["FarePerPerson"] = eng["Fare"] / eng["TicketGroupSize"].clip(lower=1)

# Deck from Cabin
if "Cabin" in eng.columns:
    eng["Deck"] = eng["Cabin"].fillna("U").str[0]

preview = [c for c in ["Title","FamilyBucket","IsAlone","Deck"] if c in eng.columns]
preview_num = [c for c in ["FamilySize","TicketGroupSize","FarePerPerson"] if c in eng.columns]
print("Engineered categorical previews:", preview)
print("Engineered numeric previews:", preview_num)
eng[[c for c in preview+preview_num]].head()""")

    code("""# Survival rate by each engineered categorical
if is_binary and preview:
    n = len(preview); ncol = 2; nrow = int(np.ceil(n/ncol))
    fig, axes = plt.subplots(nrow, ncol, figsize=(6*ncol, 3.8*nrow))
    for ax, c in zip(np.atleast_1d(axes).ravel(), preview):
        order = eng.groupby(c)[TARGET].mean().sort_values(ascending=False).index
        sns.barplot(data=eng, x=c, y=TARGET, order=order, ax=ax, hue=c,
                    legend=False, errorbar=("ci", 95))
        ax.axhline(eng[TARGET].mean(), ls="--", color="grey", lw=1)
        ax.set_title(f"{TARGET} rate by {c}"); ax.tick_params(axis="x", rotation=30)
    for ax in np.atleast_1d(axes).ravel()[n:]:
        ax.set_visible(False)
    fig.suptitle("Engineered features expose strong survival signal",
                 y=1.02, fontweight="bold")
    sns.despine(); plt.tight_layout(); plt.show()""")

    # 8. Takeaways ------------------------------------------------------------
    md("## 7 · Takeaways (auto-filled from `eda_summary.json`)")
    code("""summary_path = Path(RUN_DIR) / "eda" / "eda_summary.json"
if summary_path.exists():
    s = json.loads(summary_path.read_text())
    tgt = s.get("target", {})
    print(f"Task: {tgt.get('task')}  |  rows: {tgt.get('n_rows')}")
    if "classes" in tgt:
        print("Class balance:", tgt["classes"], "| imbalance ratio:", tgt.get("imbalance_ratio"))
    print("\\nTop |correlation| with target:")
    for k, v in list(s.get("target_correlation_top", {}).items())[:10]:
        print(f"  {k}: {v}")
    cols = s.get("columns", [])
    skew = [c["name"] for c in cols if c.get("numeric") and abs(c.get("skew",0))>1.5]
    miss = [c["name"] for c in cols if c.get("missing_pct",0)>5]
    highcard = [c["name"] for c in cols if not c.get("numeric") and c.get("n_unique",0)>30]
    print("\\nSkewed numerics (log1p/power candidates):", skew or "none")
    print("Columns >5% missing (imputation matters):", miss or "none")
    print("High-cardinality categoricals (target-encode > one-hot):", highcard or "none")
else:
    print("eda_summary.json not found — run scripts/eda.py first.")""")

    md(f"""---
*Generated {C['timestamp']} · `kaggle-ml-loop` · see the champion notebook for model results.*""")
    return cells
